services:
  - type: web
    name: osamu-group-v999
    runtime: node
    plan: free
    region: singapore
    branch: master
    rootDir: .
    buildCommand: npm ci --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: BOT_TOKEN
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: OWNER_IDS
        sync: false
      - key: PORT
        value: 10000
