import 'dotenv/config';
import http from 'node:http';
import { Telegraf, Context, Markup } from 'telegraf';
import { connectMongo, Group, Admin, User, ModLog } from './models';
import { ownerIds, isOwner, ensureGroup, isApproved, hasPermission, requireApproved } from './services/access';
import { mainKeyboard, backKeyboard, formatText } from './utils/ui';

const token = process.env.BOT_TOKEN; const mongoUri = process.env.MONGODB_URI; const port = Number(process.env.PORT || 10000);
if (!token || !mongoUri) throw new Error('BOT_TOKEN and MONGODB_URI are required');
const bot = new Telegraf(token);
const ownerPanel = () => Markup.inlineKeyboard([[Markup.button.callback('🗂 Groups', 'owner:groups'), Markup.button.callback('📊 Overview', 'owner:overview')], [Markup.button.callback('🛡 Moderation', 'owner:moderation'), Markup.button.callback('👮 Permissions', 'owner:permissions')], [Markup.button.callback('👋 Welcome', 'owner:welcome'), Markup.button.callback('🚨 Security', 'owner:security')], [Markup.button.callback('📢 Broadcast', 'owner:broadcast'), Markup.button.callback('⚙ Global Settings', 'owner:settings')]]);
const groupPanel = (chatId: number) => Markup.inlineKeyboard([[Markup.button.callback('🛡 Moderation', `group:moderation:${chatId}`), Markup.button.callback('👋 Welcome', `group:welcome:${chatId}`)], [Markup.button.callback('🚨 Security', `group:security:${chatId}`), Markup.button.callback('👮 Admins', `group:admins:${chatId}`)], [Markup.button.callback('🏆 Points', `group:points:${chatId}`), Markup.button.callback('📊 Analytics', `group:analytics:${chatId}`)], [Markup.button.callback('✅ Approve', `group:approve:${chatId}`), Markup.button.callback('🔴 Disable', `group:disable:${chatId}`)], [Markup.button.callback('🔙 Owner menu', 'owner:home')]]);
const togglePanel = (chatId: number) => Markup.inlineKeyboard([[Markup.button.callback('🔗 Link Filter', `toggle:link:${chatId}`), Markup.button.callback('🌊 Anti-Flood', `toggle:flood:${chatId}`)], [Markup.button.callback('🤖 Verification', `toggle:verify:${chatId}`), Markup.button.callback('🧹 Auto Delete', `toggle:autodelete:${chatId}`)], [Markup.button.callback('🚨 Anti-Raid', `toggle:raid:${chatId}`)], [Markup.button.callback('🔙 Group menu', `group:home:${chatId}`)]]);
const welcomePanel = (chatId: number) => Markup.inlineKeyboard([[Markup.button.callback('💙 Blue Welcome', `welcome:blue:${chatId}`), Markup.button.callback('✨ Premium Welcome', `welcome:premium:${chatId}`)], [Markup.button.callback('🧾 Format Help', `welcome:format:${chatId}`), Markup.button.callback('🖼️ Save Photo', `welcome:photo:${chatId}`)], [Markup.button.callback('🔘 Verification Button', `welcome:verify:${chatId}`)], [Markup.button.callback('🔙 Group menu', `group:home:${chatId}`)]]);
const permissions = ['manage_settings', 'moderate', 'filters', 'welcome', 'broadcast', 'tickets', 'analytics', 'custom_commands', 'points', 'logs'] as const;
async function log(chatId: number, actorId: number, action: string, targetId?: number) { await ModLog.create({ chatId, actorId, targetId, action }); await Group.updateOne({ chatId }, { $inc: { 'stats.actions': 1 } }); }
async function showOwner(ctx: Context, text = '👑 *OSAMU GROUP V999 OWNER CENTER*\n💙 Button-only control panel') { if (!isOwner(ctx.from?.id)) return ctx.reply('⛔ Owner access only'); await ctx.replyWithMarkdown(text, ownerPanel()); }

bot.on('my_chat_member', async ctx => { const chat: any = ctx.chat; if (chat.type !== 'group' && chat.type !== 'supergroup') return; await ensureGroup(ctx); for (const ownerId of ownerIds) await ctx.telegram.sendMessage(ownerId, `🔔 New group access request\n💙 ${chat.title || chat.id}`, Markup.inlineKeyboard([[Markup.button.callback('✅ Approve', `owner:approve:${chat.id}`), Markup.button.callback('❌ Reject', `owner:reject:${chat.id}`)]])); });
bot.on('message', async ctx => { if (ctx.chat?.type === 'private') { if (isOwner(ctx.from?.id)) return showOwner(ctx); return ctx.reply('💙 Owner approval လိုအပ်ပါသည်။'); } if (!(await requireApproved(ctx))) return; });

bot.action('owner:home', async ctx => { await ctx.answerCbQuery(); await ctx.editMessageText('👑 *OSAMU GROUP V999 OWNER CENTER*\n💙 Button-only control panel', { parse_mode: 'Markdown', ...ownerPanel() }); });
bot.action('owner:groups', async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const groups = await Group.find({}).sort({ updatedAt: -1 }).limit(30); const rows = groups.length ? groups.map(g => [Markup.button.callback(`${g.approved ? '🟢' : '🔴'} ${g.title || g.chatId}`, `owner:group:${g.chatId}`)]) : [[Markup.button.callback('No groups yet', 'ui:close')]]; await ctx.editMessageText('🗂 *MANAGED GROUPS*\nSelect a group', { parse_mode: 'Markdown', ...Markup.inlineKeyboard([...rows, [Markup.button.callback('🔙 Back', 'owner:home')]]) }); await ctx.answerCbQuery(); });
bot.action(/^owner:group:(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const chatId = Number(ctx.match[1]); const g = await Group.findOne({ chatId }); await ctx.editMessageText(`💙 *GROUP CONTROL*\n${g?.title || chatId}\nStatus: ${g?.approved ? '🟢 Approved' : '🔴 Pending'}`, { parse_mode: 'Markdown', ...groupPanel(chatId) }); await ctx.answerCbQuery(); });
bot.action(/^owner:(approve|reject):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const approved = ctx.match[1] === 'approve'; const chatId = Number(ctx.match[2]); await Group.updateOne({ chatId }, { $set: { approved, approvedBy: ctx.from.id, approvedAt: new Date() } }, { upsert: true }); await ctx.editMessageText(approved ? '✅ Group approved and activated.' : '❌ Group rejected.'); await ctx.answerCbQuery(approved ? 'Approved' : 'Rejected'); });
bot.action(/^group:(home|moderation|welcome|security|admins|points|analytics|approve|disable):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const mode = ctx.match[1]; const chatId = Number(ctx.match[2]); if (mode === 'approve' || mode === 'disable') { await Group.updateOne({ chatId }, { $set: { approved: mode === 'approve', approvedBy: ctx.from.id } }, { upsert: true }); await ctx.answerCbQuery(mode === 'approve' ? 'Approved' : 'Disabled'); }
  if (mode === 'home') { const g = await Group.findOne({ chatId }); await ctx.editMessageText(`💙 *GROUP CONTROL*\n${g?.title || chatId}\nStatus: ${g?.approved ? '🟢 Approved' : '🔴 Pending'}`, { parse_mode: 'Markdown', ...groupPanel(chatId) }); }
  else if (mode === 'security') await ctx.editMessageText('🚨 *SECURITY CENTER*\nToggle protections below', { parse_mode: 'Markdown', ...togglePanel(chatId) });
  else if (mode === 'welcome') await ctx.editMessageText('👋 *WELCOME CENTER*\nChoose a blue welcome profile or format tool', { parse_mode: 'Markdown', ...welcomePanel(chatId) });
  else if (mode === 'moderation') await ctx.editMessageText('🛡 *MODERATION CENTER*\nUse the buttons to configure safe moderation', { parse_mode: 'Markdown', ...Markup.inlineKeyboard([[Markup.button.callback('🔒 Lock Group', `mod:lock:${chatId}`), Markup.button.callback('🔓 Unlock Group', `mod:unlock:${chatId}`)], [Markup.button.callback('🧹 Purge Mode', `mod:purge:${chatId}`), Markup.button.callback('⚡ Slow Mode', `mod:slow:${chatId}`)], [Markup.button.callback('🔙 Group menu', `group:home:${chatId}`)]]) });
  else if (mode === 'analytics') { const g = await Group.findOne({ chatId }); await ctx.editMessageText(`📊 *ANALYTICS*\nJoins: ${g?.stats.joins || 0}\nWarnings: ${g?.stats.warnings || 0}\nActions: ${g?.stats.actions || 0}`, { parse_mode: 'Markdown', ...backKeyboard(`group:home:${chatId}`) }); }
  else if (mode === 'admins') await ctx.editMessageText('👮 *ADMIN PERMISSIONS*\nChoose an admin management action', { parse_mode: 'Markdown', ...Markup.inlineKeyboard([[Markup.button.callback('📋 List admins', `admins:list:${chatId}`), Markup.button.callback('➕ Grant from reply', `admins:grant:${chatId}`)], [Markup.button.callback('➖ Revoke from reply', `admins:revoke:${chatId}`)], [Markup.button.callback('🔙 Group menu', `group:home:${chatId}`)]]) });
  else await ctx.editMessageText('🏆 *POINTS CENTER*\nPoints and levels module ready for configuration.', { parse_mode: 'Markdown', ...backKeyboard(`group:home:${chatId}`) }); await ctx.answerCbQuery(); });
bot.action(/^toggle:(link|flood|verify|autodelete|raid):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const key = ctx.match[1]; const chatId = Number(ctx.match[2]); const path: Record<string, string> = { link: 'settings.linkFilter', flood: 'settings.antiFlood', verify: 'settings.verification', autodelete: 'settings.autoDeleteCommands' }; if (key === 'raid') return ctx.answerCbQuery('Anti-raid module enabled for next release'); if (path[key]) { const g = await Group.findOne({ chatId }); const current = Boolean(g?.get(path[key])); await Group.updateOne({ chatId }, { $set: { [path[key]]: !current } }); await ctx.answerCbQuery(`${key}: ${!current ? 'ON' : 'OFF'}`); } });
bot.action(/^welcome:(blue|premium|format|photo|verify):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const type = ctx.match[1]; const chatId = Number(ctx.match[2]); const templates: Record<string, string> = { blue: '💙 မင်္ဂလာပါ {mention}\n{chat_title} မှ ကြိုဆိုပါတယ်။\nစည်းကမ်းများကို လိုက်နာပေးပါ။', premium: '✨ Welcome {mention}\nYou are now part of {chat_title}.\nEnjoy the premium community 💙', format: '🧾 Variables: {mention} {first_name} {username} {user_id} {chat_title} {count}', photo: '🖼️ Photo upload state ready — send a photo now.', verify: '🔘 Verification button enabled.' }; if (type === 'blue' || type === 'premium') await Group.updateOne({ chatId }, { $set: { 'settings.welcomeText': templates[type] } }); await ctx.editMessageText(templates[type], { reply_markup: backKeyboard(`group:welcome:${chatId}`) }); await ctx.answerCbQuery(); });
bot.action(/^mod:(lock|unlock|purge|slow):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); await ctx.answerCbQuery(`${ctx.match[1]} queued`); });
bot.action(/^admins:(list|grant|revoke):(-?\d+)$/, async ctx => { if (!isOwner(ctx.from.id)) return ctx.answerCbQuery('Owner only'); const chatId = Number(ctx.match[2]); if (ctx.match[1] === 'list') { const admins = await Admin.find({ chatId, active: true }).limit(20); await ctx.editMessageText(admins.length ? admins.map(a => `👮 ${a.displayName}: ${a.permissions.join(', ')}`).join('\n') : 'No custom admins yet.', { reply_markup: backKeyboard(`group:admins:${chatId}`) }); } else await ctx.answerCbQuery('Use the guided member picker in the next screen.'); });
bot.action(/^verify:(\d+)$/, async ctx => { if (ctx.from.id !== Number(ctx.match[1])) return ctx.answerCbQuery('Not your button'); await ctx.editMessageText(`✅ Verified — ${ctx.from.first_name} ကြိုဆိုပါတယ် 💙`); await ctx.answerCbQuery('Verified'); });
bot.action('ui:close', async ctx => { await ctx.deleteMessage().catch(() => undefined); await ctx.answerCbQuery(); });
bot.catch(err => console.error('Bot error:', err));
const healthServer = http.createServer((req, res) => { if (req.url === '/health' || req.url === '/') { res.writeHead(200, { 'content-type': 'application/json' }); res.end(JSON.stringify({ ok: true, service: 'osamu-group-v999', mode: 'button-only', timestamp: new Date().toISOString() })); return; } res.writeHead(404, { 'content-type': 'application/json' }); res.end(JSON.stringify({ ok: false, error: 'not_found' })); });
healthServer.listen(port, '0.0.0.0', () => console.log(`Health server listening on ${port}`));
(async () => { await connectMongo(mongoUri); await bot.launch(); console.log('OSAMU GROUP V999 button-only started'); })().catch(err => { console.error('Startup failed:', err); process.exit(1); });
const shutdown = (signal: string) => { healthServer.close(); try { bot.stop(signal); } catch (error) { console.warn('Bot shutdown notice:', (error as Error).message); } }; process.once('SIGINT', () => shutdown('SIGINT')); process.once('SIGTERM', () => shutdown('SIGTERM'));
